### ISSUE TITLE
links to RapidBlog posts include extra charater

### ISSUE THREAD

**Issue by girlcarew** [yourhead/sitemap#11]
The links to RapidBlog posts on a SiteMap page contain a slash before the question mark

For example 
http://marc.vos.net/index.php/?id=3986180788711167181 should be 
http://marc.vos.net/index.php?id=3986180788711167181  (no slash after php)

If you need a file you can find "A file" in the shared DropBox folder. 
If you create a new file, you must check the "Enable blog posts as items in sitemap" box on the Blog tab of the Inspector

**Comment by yourhead** [comment]
fixed in v3.2
