### ISSUE TITLE
sitemap.xml is published with the URL of the homepage having an extra "./" on the end

### ISSUE THREAD

**Issue by yourhead** [yourhead/sitemap#4]
I suspect that RW added an automatic "/" to the end of the Site URL parameter which confuses the sitemap URL generation.

**Comment by yourhead** [comment]
Verified last LogHound stable release also exhibits this bug.  Not a YourHead regression.  I feel slightly better now.  ;-)

**Comment by Rambobino** [comment]
Do you know when the bug will be fixed ? Thanks a lot.

**Comment by yourhead** [comment]
fixed in v3.2
