### ISSUE TITLE
redraw problem in Site Organization tab

### ISSUE THREAD

**Issue by girlcarew** [yourhead/sitemap#5]
1. Open a document with a sitemap.
2. Select the SiteMapPlus page in the pages & resource list.
3. Click the Site Organization tab.
4. Open the inspector.
5. Choose the page inspector tab.
6. Nothing now shows in the Site Organization tab (if it was showing it disappears).

You can show it by going to a different page and coming back. And once you get it back you can't make it go away again unless you quit and restart.

**Comment by yourhead** [comment]
i was not able to repeat this bug as i'm not sure what "the inspector" is referring to. but i'm kind of assuming it's the info-sidebar on the right side. in 2016 in RW6 this was its own floating inspector.

in that case, then this has been fixed as showing the sidebar -- or the inspector form of the sidebar -- doesn't make anything disappear.

this could also have been corrected when #3 was fixed.
